const HUB_DESIGN_STYLES = `
:host{all:initial;--hub-ink:#18191c;--hub-ink-soft:#40434a;--hub-muted:#6d7075;--hub-accent:#176653;--hub-accent-strong:#0f5140;--hub-tint:#ecf4f0;--hub-line:#e4e5e8;--hub-line-strong:#d2d4d8;--hub-surface:#fff;--hub-canvas:#f7f7f8;--hub-hover:#f0f0f2;--hub-warn-ink:#8a5a12;--hub-warn-bg:#fdf3e2;--hub-danger:#b02a2a;--hub-radius:14px;--hub-radius-sm:9px;--hub-shadow:0 1px 2px #16181c0d,0 14px 44px #16181c1f;position:fixed;right:16px;bottom:16px;z-index:2147483646;color:var(--hub-ink);font:13px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color-scheme:light}
*,*::before,*::after{box-sizing:border-box}[hidden]{display:none!important}
.panel{width:min(464px,calc(100vw - 24px));max-height:88vh;max-height:88dvh;overflow:auto;background:var(--hub-surface);border:1px solid var(--hub-line-strong);border-radius:var(--hub-radius);box-shadow:var(--hub-shadow)}
header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 20px 14px;border-bottom:1px solid var(--hub-line);background:var(--hub-surface)}
.hub-heading{min-width:0;flex:1}.hub-eyebrow{font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:var(--hub-muted);font-weight:650;margin-bottom:4px}.hub-version{font-size:10px;color:var(--hub-muted);font-variant-numeric:tabular-nums}
.hub-release{display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin-top:7px}.hub-update{display:inline-flex;align-items:center;min-height:26px;padding:2px 9px;border:1px solid var(--hub-line-strong);border-radius:99px;font-size:11px;font-weight:550;color:var(--hub-ink-soft);text-decoration:none}.hub-update:hover{background:var(--hub-hover);border-color:var(--hub-muted)}
h2{font-size:17px;line-height:1.25;letter-spacing:-.02em;margin:0;font-weight:640}h3{font-size:11px;letter-spacing:.06em;text-transform:uppercase;margin:0 0 9px;font-weight:650;color:var(--hub-muted)}p{margin:6px 0}
section,main{padding:16px 20px;border-bottom:1px solid var(--hub-line)}footer,.status{padding:14px 20px;background:var(--hub-canvas);overflow-wrap:anywhere}.muted,.card-report,.logs{color:var(--hub-muted);font-size:12px}.error,.storage-error{color:var(--hub-danger)}.notice{border-left:2px solid var(--hub-line-strong);background:var(--hub-canvas);border-radius:0 var(--hub-radius-sm) var(--hub-radius-sm) 0;padding:10px 12px;color:var(--hub-ink-soft)}
button,input,select{font:inherit}button,select{border:1px solid var(--hub-line-strong);border-radius:var(--hub-radius-sm);color:var(--hub-ink);background:var(--hub-surface);padding:8px 12px;min-height:36px}button{cursor:pointer;font-weight:550;transition:background .12s ease,border-color .12s ease}button:not(:disabled):hover{background:var(--hub-hover);border-color:var(--hub-muted)}button.primary{background:var(--hub-accent);color:#fff;border-color:var(--hub-accent)}button.primary:not(:disabled):hover{background:var(--hub-accent-strong);border-color:var(--hub-accent-strong)}button:disabled{opacity:.4;cursor:not-allowed}button.stop{color:var(--hub-danger)}button.stop:not(:disabled):hover{border-color:var(--hub-danger)}button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid var(--hub-accent);outline-offset:2px}
input[type=search]{width:100%;padding:10px 13px;border:1px solid var(--hub-line-strong);border-radius:var(--hub-radius-sm);background:var(--hub-canvas);color:var(--hub-ink)}input[type=search]:focus{background:var(--hub-surface)}input[type=checkbox]{accent-color:var(--hub-accent);flex:none;width:15px;height:15px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 0}.cards{max-height:180px;overflow:auto}.card{display:flex;align-items:flex-start;gap:9px;padding:9px 0;overflow-wrap:anywhere}.card+.card{border-top:1px solid var(--hub-line)}.card input{margin-top:3px}.card-info{min-width:0;flex:1}
.offers{max-height:260px;overflow:auto;margin-top:10px}.offer{display:block;padding:13px 0;border-bottom:1px solid var(--hub-line);overflow-wrap:anywhere}.offer:last-child{border-bottom:0}.offer small{display:block;color:var(--hub-muted);margin-top:5px}.offer-title{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;font-weight:550}.offer-title button{flex-shrink:0;font-weight:550}.badges{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.badge{border-radius:99px;background:var(--hub-canvas);border:1px solid var(--hub-line);color:var(--hub-ink-soft);padding:2px 8px;font-size:11px;font-weight:550}.badge.enrolled{background:var(--hub-tint);border-color:#cadfd6;color:var(--hub-accent)}.badge.unconfirmed,.badge.failed{background:var(--hub-warn-bg);border-color:#efdcb8;color:var(--hub-warn-ink)}.card-counts,.offer-counts,.offer-target{color:var(--hub-ink-soft);font-size:12px}.logs{max-height:90px;overflow:auto}a{color:var(--hub-accent);text-underline-offset:3px}
.hub-search-launcher{display:flex;align-items:center;justify-content:space-between;gap:10px;width:100%;border:0;border-bottom:1px solid var(--hub-line);border-radius:0;background:var(--hub-tint);padding:11px 20px;color:var(--hub-accent);text-align:left;font-weight:600}.hub-search-launcher:not(:disabled):hover{background:#e2eee8;border-color:var(--hub-line)}.hub-search-launcher span:last-child{font-size:11px;font-weight:450;color:var(--hub-ink-soft)}a.hub-search-launcher{background:var(--hub-surface);color:var(--hub-ink);font-weight:550;text-decoration:none}a.hub-search-launcher:hover{background:var(--hub-hover)}
.hub-step h3{color:var(--hub-muted)}.hub-scope-hint{margin-top:0}.hub-action-reason{font-size:12px;color:var(--hub-muted);margin-top:10px}.hub-clear-search{font-size:11px;min-height:28px;padding:4px 9px;margin-top:6px}.hub-search-rule{font-size:11px}.hub-step .actions{margin-bottom:8px}
@media(max-width:500px){:host{right:12px;bottom:12px}header{padding:14px 16px}section,main,footer,.status{padding:14px 16px}}
`;
