const HUB_DESIGN_STYLES = `
:host{all:initial;--hub-ink:#18191c;--hub-ink-soft:#40434a;--hub-muted:#6d7075;--hub-accent:#176653;--hub-accent-strong:#0f5140;--hub-tint:#ecf4f0;--hub-accent-line:#c6ddd3;--hub-line:#e6e7ea;--hub-line-strong:#d3d5d9;--hub-surface:#fff;--hub-canvas:#f7f7f8;--hub-hover:#f0f1f3;--hub-warn-ink:#8a5a12;--hub-warn-bg:#fdf4e4;--hub-warn-line:#efdcb8;--hub-danger:#b02a2a;--hub-danger-bg:#fdf0f0;--hub-danger-line:#f0caca;--hub-radius:14px;--hub-radius-sm:8px;--hub-shadow:0 1px 2px #16181c0f,0 10px 32px #16181c1f,0 0 0 1px #16181c08;--hub-search-icon:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Ccircle cx='7' cy='7' r='4.75' fill='none' stroke='black' stroke-width='1.6'/%3E%3Cpath d='m10.5 10.5 3.5 3.5' stroke='black' stroke-width='1.6' stroke-linecap='round'/%3E%3C/svg%3E");position:fixed;right:16px;bottom:16px;z-index:2147483646;color:var(--hub-ink);font:13px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color-scheme:light;-webkit-font-smoothing:antialiased}
*,*::before,*::after{box-sizing:border-box}[hidden]{display:none!important}
.panel{counter-reset:hub-step;display:flex;flex-direction:column;width:min(440px,calc(100vw - 24px));max-height:88vh;max-height:88dvh;overflow:hidden;background:var(--hub-surface);border:1px solid var(--hub-line-strong);border-radius:var(--hub-radius);box-shadow:var(--hub-shadow)}
.panel>#body,.panel>#content,.panel>#hub-entry-content{flex:1 1 auto;min-height:0;overflow:auto;overscroll-behavior:contain}
.panel:has(>#body[hidden],>#content[hidden],>#hub-entry-content[hidden]){width:auto;max-width:calc(100vw - 24px)}.panel:has(>#body[hidden],>#content[hidden],>#hub-entry-content[hidden])>header{border-bottom:0}
header{flex:none;display:flex;align-items:center;gap:11px;padding:11px 10px 11px 14px;border-bottom:1px solid var(--hub-line);background:var(--hub-surface)}
.hub-mark{flex:none;position:relative;width:28px;height:20px;border-radius:5px;background:var(--hub-accent);box-shadow:inset 0 0 0 1px #00000014}.hub-mark::before{content:'';position:absolute;left:0;right:0;top:5px;height:3px;background:#ffffff55}.hub-mark::after{content:'';position:absolute;left:5px;bottom:4px;width:8px;height:2px;border-radius:1px;background:#ffffffb0}
.hub-heading{min-width:0;flex:1}.hub-topline{display:flex;align-items:center;flex-wrap:wrap;gap:0 7px;font-size:10.5px;line-height:1.5;color:var(--hub-muted)}
.hub-eyebrow{font-size:10px;letter-spacing:.12em;text-transform:uppercase;font-weight:650;color:var(--hub-muted)}.hub-release{display:inline-flex;align-items:center;gap:7px}.hub-release::before{content:'·';content:'·'/''}.hub-version{font-variant-numeric:tabular-nums}
.hub-update{display:inline-flex;align-items:center;min-height:20px;padding:0 5px;margin:0 -5px;border-radius:5px;color:var(--hub-accent);font-weight:600;text-decoration:none}.hub-update:hover{background:var(--hub-tint);text-decoration:underline}
h2{font-size:15px;line-height:1.3;letter-spacing:-.01em;margin:0;font-weight:650;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
header>button{flex:none;width:32px;height:32px;min-height:32px;padding:0;border-color:transparent;background:transparent;color:var(--hub-muted);font-size:18px;font-weight:400;line-height:1}header>button:not(:disabled):hover{background:var(--hub-hover);border-color:transparent;color:var(--hub-ink)}
h3{font-size:11px;letter-spacing:.06em;text-transform:uppercase;margin:0 0 8px;font-weight:650;color:var(--hub-muted)}p{margin:6px 0}
section,main{padding:14px 16px 16px;border-bottom:1px solid var(--hub-line)}
.hub-step>h3{display:flex;align-items:center;gap:8px}.hub-step>h3::before{counter-increment:hub-step;content:counter(hub-step);content:counter(hub-step)/'';display:inline-grid;place-items:center;flex:none;width:18px;height:18px;border-radius:50%;background:var(--hub-hover);color:var(--hub-ink-soft);font-size:10px;letter-spacing:0}
.muted,.card-report,.logs{color:var(--hub-muted);font-size:12px}.hub-scope-hint{margin:0 0 6px}.hub-fine-print{font-size:11.5px;margin:6px 0 0}.hub-scope-actions{margin:4px 0 8px}.error,.storage-error{color:var(--hub-danger)}
.notice{margin:10px 0 0;border-left:2px solid var(--hub-line-strong);background:var(--hub-canvas);border-radius:0 var(--hub-radius-sm) var(--hub-radius-sm) 0;padding:8px 10px;color:var(--hub-ink-soft);font-size:12px}
a{color:var(--hub-accent);text-underline-offset:3px}
button,input,select{font:inherit}button,select{min-height:34px;padding:6px 12px;border:1px solid var(--hub-line-strong);border-radius:var(--hub-radius-sm);color:var(--hub-ink);background:var(--hub-surface)}
button{cursor:pointer;font-weight:550;transition:background-color .12s ease,border-color .12s ease,color .12s ease}button:not(:disabled):hover{background:var(--hub-hover);border-color:var(--hub-muted)}
button.primary{background:var(--hub-accent);color:#fff;border-color:var(--hub-accent);box-shadow:0 1px 2px #0f514029}button.primary:not(:disabled):hover{background:var(--hub-accent-strong);border-color:var(--hub-accent-strong)}
button:disabled{cursor:not-allowed;color:var(--hub-muted);background:var(--hub-canvas);border-color:var(--hub-line);box-shadow:none}
button.stop{color:var(--hub-danger);border-color:var(--hub-danger-line)}button.stop:not(:disabled):hover{background:var(--hub-danger-bg);border-color:var(--hub-danger)}
button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid var(--hub-accent);outline-offset:2px}
.hub-button{display:inline-flex;align-items:center;justify-content:center;min-height:34px;padding:6px 12px;border:1px solid var(--hub-line-strong);border-radius:var(--hub-radius-sm);background:var(--hub-surface);color:var(--hub-ink);font-weight:550;text-decoration:none}.hub-button:hover{background:var(--hub-hover)}.hub-button.primary{background:var(--hub-accent);border-color:var(--hub-accent);color:#fff}.hub-button.primary:hover{background:var(--hub-accent-strong)}
input[type=checkbox]{accent-color:var(--hub-accent);flex:none;width:15px;height:15px;margin:2px 0 0;cursor:pointer}input[type=checkbox]:disabled{cursor:not-allowed}
.actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 0}
.hub-toolbar{display:flex;gap:8px;padding:10px 16px;border-bottom:1px solid var(--hub-line);background:var(--hub-canvas)}
.hub-toolbar>*{flex:1 1 0;min-width:0;display:inline-flex;align-items:center;justify-content:center;gap:6px;min-height:32px;padding:5px 10px;border:1px solid var(--hub-line-strong);border-radius:var(--hub-radius-sm);background:var(--hub-surface);color:var(--hub-ink);font-size:12px;font-weight:550;line-height:1.3;text-align:center;text-decoration:none}.hub-toolbar>*:hover{background:var(--hub-hover);border-color:var(--hub-muted)}
.hub-search-launcher::before{content:'';flex:none;width:12px;height:12px;background:currentColor;-webkit-mask:var(--hub-search-icon) center/contain no-repeat;mask:var(--hub-search-icon) center/contain no-repeat}.hub-offers-link::after{content:'→';content:'→'/'';color:var(--hub-muted)}
.cards{margin:4px -8px 0}.card{display:flex;align-items:flex-start;gap:10px;padding:7px 8px;border-radius:var(--hub-radius-sm);overflow-wrap:anywhere}label.card{cursor:pointer}label.card:hover,.cards>.card:hover{background:var(--hub-hover)}section>label.card{margin:6px -8px 0}.card-info{min-width:0;flex:1}
.hub-command{position:sticky;top:0;z-index:2;margin:-4px -16px 0;padding:8px 16px 12px;background:var(--hub-surface);box-shadow:0 1px 0 var(--hub-line)}.hub-primary-actions{margin:0}.hub-primary-actions>button{flex:1 1 auto}
.hub-action-reason{margin:10px 0 0;padding:8px 10px;border-radius:var(--hub-radius-sm);background:var(--hub-canvas);color:var(--hub-ink-soft);font-size:12px}
.hub-progress{position:relative;height:4px;margin:10px 0 0;border-radius:99px;background:var(--hub-hover);overflow:hidden}.hub-progress>span{position:absolute;top:0;bottom:0;left:0;width:var(--hub-progress,0%);border-radius:inherit;background:var(--hub-accent);transition:width .3s ease}.hub-progress.indeterminate>span{width:35%;animation:hub-progress-sweep 1.3s ease-in-out infinite}
@keyframes hub-progress-sweep{from{left:-35%}to{left:100%}}
.hub-status:not(:empty),.hub-storage-error:not(:empty){margin:10px 0 0;padding:8px 10px;border-left:3px solid var(--hub-line-strong);border-radius:0 var(--hub-radius-sm) var(--hub-radius-sm) 0;background:var(--hub-canvas);color:var(--hub-ink);font-size:12px;overflow-wrap:anywhere}.hub-storage-error:not(:empty){border-left-color:var(--hub-danger);background:var(--hub-danger-bg);color:var(--hub-danger)}
.hub-search-field{position:relative;margin:12px 0 0}.hub-search-field::before{content:'';position:absolute;left:11px;top:11px;width:14px;height:14px;background:var(--hub-muted);-webkit-mask:var(--hub-search-icon) center/contain no-repeat;mask:var(--hub-search-icon) center/contain no-repeat;pointer-events:none}
input[type=search]{width:100%;height:36px;padding:0 12px 0 32px;border:1px solid var(--hub-line-strong);border-radius:var(--hub-radius-sm);background:var(--hub-canvas);color:var(--hub-ink);-webkit-appearance:none;appearance:none}input[type=search]:hover{border-color:var(--hub-muted)}input[type=search]:focus{background:var(--hub-surface)}input[type=search]::-webkit-search-cancel-button{-webkit-appearance:none;display:none}.hub-search-field:has(.hub-clear-search:not([hidden]))>input{padding-right:92px}
.hub-clear-search{position:absolute;right:4px;top:4px;height:28px;min-height:28px;padding:0 8px;border-color:transparent;background:transparent;color:var(--hub-muted);font-size:11.5px}.hub-clear-search:not(:disabled):hover{border-color:transparent;color:var(--hub-ink)}
.hub-search-rule{font-size:11.5px;margin:6px 0 0}.hub-counts{margin:10px 0 0;font-size:12px;font-variant-numeric:tabular-nums}
.hub-selection-bar{align-items:center;gap:4px;margin:10px 0 0;padding:4px;border:1px solid var(--hub-line);border-radius:10px;background:var(--hub-canvas)}.hub-selection-bar>button{min-height:30px;padding:4px 10px;font-size:12px;border-color:transparent;background:transparent}.hub-selection-bar>button:first-child{margin-right:auto;background:var(--hub-surface);border-color:var(--hub-line-strong)}.hub-selection-bar>button:disabled{background:transparent;border-color:transparent}.hub-selection-bar>button:first-child:disabled{border-color:var(--hub-line)}
.offers{margin:6px 0 0}.offer{display:block;padding:11px 0;border-bottom:1px solid var(--hub-line);overflow-wrap:anywhere}.offer:last-child{border-bottom:0}.offer-row{display:flex;align-items:flex-start;gap:10px}label.offer{cursor:pointer}.offer-body{min-width:0;flex:1}
.offer-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.offer-merchant{font-weight:600}.offer-value{margin-top:1px;color:var(--hub-ink-soft)}.offer small{display:block;margin-top:3px;color:var(--hub-muted);font-size:11.5px}
.offer-status,.badge{display:inline-flex;align-items:center;gap:5px;flex:none;padding:1px 8px;border:1px solid var(--hub-line);border-radius:99px;background:var(--hub-surface);color:var(--hub-ink-soft);font-size:11px;font-weight:550;line-height:1.6;white-space:nowrap}
.offer-status.available::before{content:'';width:6px;height:6px;border-radius:50%;background:var(--hub-accent)}.offer-status.added,.badge.enrolled{background:var(--hub-tint);border-color:var(--hub-accent-line);color:var(--hub-accent-strong)}.offer-status.review,.badge.unconfirmed,.badge.failed{background:var(--hub-warn-bg);border-color:var(--hub-warn-line);color:var(--hub-warn-ink)}.offer-status.skipped{border-color:transparent;background:var(--hub-canvas);color:var(--hub-muted)}
.offer-title{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;font-weight:600}.offer-title button{flex:none;min-height:28px;padding:3px 10px;font-size:12px}.offer>p{margin:3px 0 0;font-size:12px}.badges{display:flex;gap:4px;flex-wrap:wrap;margin-top:8px}.badge{white-space:normal}
.card-counts,.offer-counts{color:var(--hub-ink-soft);font-size:12px}.offer-target{color:var(--hub-ink);font-size:12px}.hub-empty-note{margin:12px 0 4px;padding:14px 12px;border:1px dashed var(--hub-line-strong);border-radius:10px;text-align:center}.hub-list-limit{margin:10px 0 0;text-align:center}
footer,.status{padding:12px 16px 14px;background:var(--hub-canvas);overflow-wrap:anywhere}footer>p:first-child{margin-top:0}.logs{max-height:120px;overflow:auto}
details{margin-top:6px;font-size:12px;color:var(--hub-muted)}summary{cursor:pointer;width:fit-content;padding:2px 0;border-radius:4px;color:var(--hub-ink-soft);font-weight:550}summary:hover{color:var(--hub-ink)}details button{min-height:30px;padding:4px 10px;font-size:12px}
@media(max-width:500px){:host{right:12px;bottom:12px}header{padding:10px 8px 10px 12px}section,main,footer,.status,.hub-toolbar{padding-left:14px;padding-right:14px}.hub-command{margin:0 -14px;padding-left:14px;padding-right:14px}}
@media(prefers-reduced-motion:reduce){button{transition:none}.hub-progress>span{transition:none}.hub-progress.indeterminate>span{animation:none;left:0;width:100%;opacity:.45}}
`;
